### ISSUE TITLE
Link to the tSNE map not working

### ISSUE THREAD

**Issue by pietmolenaar** [antronerds/r2-training-courses#2]
Apparently the parameters for the automagic link to the tSNE map in the course have changed. What are the correct parameters?
This has to be fixed before the start of the course

**Comment by jankoster** [comment]
This was caused by the server upgrade. the md5 on the current set is no longer the same.
Solution can be 3fold:
1: we rename the tsne map file to the new md5 sum
2: we generate a new tsne from within R2 (I used this one, that solves the issue for the lifecycle of the new server) <-
3: we link to the file, but one step earlier.
